### ISSUE TITLE
 return np.array(trials, dtype=np.float64).reshape((len(trials),) + trials[0].shape + (1,)), np.array(labels, dtype=np.float64) index error

### ISSUE THREAD

**Issue by sumon3255** [SuperBruceJia/EEG-DL#18]
can any one solve this issue?

**Comment by sumon3255** [comment]
@SuperBruceJia

**Comment by SuperBruceJia** [comment]
> can any one solve this issue?

Hi, morning. I think this issue was caused by the versions of Python and pyEDFlib.

**Problem**: *IndexError: list index out of range*
**Solution**: *At the time, I used Python==2.7 and pyEDFlib==0.1.11*
    
To solve this issue, first of all, please double-check the Python Environment. ***Python 2.7 Environment is required.*** Besides, please install ***0.1.11*** version of ***pyEDFlib*** Python package. The installation instruction is as follows:
    
```
$ pip install pyEDFlib==0.1.11
```

If you still get this problem, please let me know.

Best regards,

Shuyue
Nov. 8th, 2022
